### ISSUE TITLE
Memory leak somewhere!

### ISSUE THREAD

**Issue by Maikatura** [Bukk94/KickLib#12]
Hi, I have been playing around with KickLib for a while now.

There is just one issue.
When I run the bot for a long time the allocation that the bot takes up in memory goes up by a lot.
I had my bot running for about 17 hours and it gets up to 3 GB and it usually runs around 400 MB without a KickLib bot added. 
I know that its not my own code since I reuses a lot of code template from my twitch bot. So i haven't had the time too look at it too much but there is a memory leak somewhere in KickLib.

Version: 0.1.12

**Comment by Bukk94** [comment]
Hi, are you using KickLib API or Client? Or both? Can you provide some code snippets please?

**Comment by Maikatura** [comment]
The client only

**Comment by Bukk94** [comment]
@Maikatura So far I was not able to locate the issue. Based on what I saw there are no indications of memory leaks.

Do you have highly frequent chat (processing a lot of messages) or just a few messages?

One of the potential memory leaks can happen in your `Initialize` method. If you call this method multiple times, it will overwrite the previous instance 
` myClient = new KickClient();`
but previous instance won't be collected by GC because of the hooked event handlers and possibly active connection.

**Comment by Maikatura** [comment]
Made my own wrapper base on the one proviced with nullable EventHandlers and have been running it for 3 days now without running into the memory leak problems. I have not done any changed to my KickBotClient  class.
